name: Build & Test  
on: [push, pull_request]  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Install Dependencies  
        run: |  
          sudo apt-get update
          sudo apt-get install -y antlr4 llvm-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision onnxruntime-gpu
      - name: Run Tests  
        run: |
          pytest tests/ --verbose
          python benchmarks/performance_test.py
  
  compile:  
    runs-on: ubuntu-latest  # Changed from quantum_sim to realistic hardware
    steps:  
      - name: Compile  
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)